apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calc-backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: calc-backend
    spec:
      containers:
        - name: calc-backend
          image: mycontainerregistrywaltl.azurecr.io/calcbackend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: calc-backend
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: calc-backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calc-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
#  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: calc-frontend
    spec:
      containers:
        - name: calc-frontend
          image: mycontainerregistrywaltl.azurecr.io/calcfrontend:v1
          ports:
            - containerPort: 80
#          resources:
#            requests:
#              cpu: 250m
#            limits:
#              cpu: 500m
          env:
            - name: "ENDPOINT"
              value: "calc-backend"
            - name: "PORT"
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: calc-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: calc-frontend
